name: SQL review on pull request using bytebase-action image

on:
  pull_request:
    branches:
      - main
    paths:
      - "schema/*.sql"

jobs:
  check-release-on-prod:
    permissions:
        pull-requests: write # write permission required to allow the action writes the check results to the comment.
    # runs-on: ubuntu-latest # use self-hosted machines if your Bytebase runs in internal networks.
    runs-on: self-hosted
    container:
    #   image: docker://bytebase/bytebase-action:latest
      image: docker://bytebase/bytebase-action:3.12.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check release
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # set GITHUB_TOKEN because the 'Check release' step needs it to comment the pull request with check results.
            BYTEBASE_URL: http://localhost:8080
            BYTEBASE_SERVICE_ACCOUNT: api@service.bytebase.com # set service account via environment variable
            BYTEBASE_SERVICE_ACCOUNT_SECRET: ${{ secrets.BYTEBASE_SERVICE_ACCOUNT_SECRET }} # set service account secret via environment variable
            BYTEBASE_PROJECT: "projects/project-test"
            BYTEBASE_TARGETS: "instances/prod-sample-instance/databases/school_prod"
            FILE_PATTERN: "schema/*.sql"
        run: |
          bytebase-action check --url=${{ env.BYTEBASE_URL }} --project=${{ env.BYTEBASE_PROJECT }} --targets=${{ env.BYTEBASE_TARGETS }} --file-pattern=${{ env.FILE_PATTERN }}